import Manager
import Object
from DBAccess import IntArrayValue as IntArrayValue, RealArrayValue as RealArrayValue
from typing import Any, ItemsView, Iterable, KeysView, ValuesView


class ColorManager(Manager.AdamsManager):
    def values(self) -> ValuesView[Color]: ...
    def keys(self) -> KeysView[str]: ...
    def items(self) -> ItemsView[str, Color]: ...
    def __getitem__(self, name: str) -> Color: ...
    def __iter__(self) -> Iterable[Color]: ...
    def values_full(self) -> ValuesView[Color]: ...
    def keys_full(self) -> KeysView[str]: ...
    def items_full(self) -> ItemsView[str, Color]: ...


class Color(Object.ObjectBase):
    def __init__(self, _DBKey) -> None: ...
    rgb: Any
