import Manager
import Object
from typing import Any, ItemsView, Iterable, KeysView, ValuesView


class DesignPointManager(Manager.AdamsManager):
    def values(self) -> ValuesView[DesignPoint]: ...
    def keys(self) -> KeysView[str]: ...
    def items(self) -> ItemsView[str, DesignPoint]: ...
    def __getitem__(self, name: str) -> DesignPoint: ...
    def __iter__(self) -> Iterable[DesignPoint]: ...
    def values_full(self) -> ValuesView[DesignPoint]: ...
    def keys_full(self) -> KeysView[str]: ...
    def items_full(self) -> ItemsView[str, DesignPoint]: ...


class DesignPoint(Object.Object):
    def __init__(self, _DBKey) -> None: ...
    location: Any
    comments: Any
