import Manager
import Object
from typing import Any, ItemsView, Iterable, KeysView, ValuesView


class LibraryManager(Manager.AdamsManager):
    def values(self) -> ValuesView[Library]: ...
    def keys(self) -> KeysView[str]: ...
    def items(self) -> ItemsView[str, Library]: ...
    def __getitem__(self, name: str) -> Library: ...
    def __iter__(self) -> Iterable[Library]: ...
    def values_full(self) -> ValuesView[Library]: ...
    def keys_full(self) -> KeysView[str]: ...
    def items_full(self) -> ItemsView[str, Library]: ...


class Library(Object.ObjectBase):
    Libraries: Any
    Materials: Any
    UserDefinedElements: Any
    def __init__(self, _DBKey) -> None: ...


class AttributesLibraryManager(Manager.AdamsManager):
    def values(self) -> ValuesView[Attributes_Library]: ...
    def keys(self) -> KeysView[str]: ...
    def items(self) -> ItemsView[str, Attributes_Library]: ...
    def __getitem__(self, name: str) -> Attributes_Library: ...
    def __iter__(self) -> Iterable[Attributes_Library]: ...
    def values_full(self) -> ValuesView[Attributes_Library]: ...
    def keys_full(self) -> KeysView[str]: ...
    def items_full(self) -> ItemsView[str, Attributes_Library]: ...


class Attributes_Library(Object.ObjectBase):
    Colors: Any
    def __init__(self, _DBKey) -> None: ...
