import Manager
import Object
from typing import ItemsView, Iterable, KeysView, List, ValuesView


class MaterialManager(Manager.AdamsManager):
    def values(self) -> ValuesView[Material]: ...
    def keys(self) -> KeysView[str]: ...
    def items(self) -> ItemsView[str, Material]: ...
    def __getitem__(self, name: str) -> Material: ...
    def __iter__(self) -> Iterable[Material]: ...
    def values_full(self) -> ValuesView[Material]: ...
    def keys_full(self) -> KeysView[str]: ...
    def items_full(self) -> ItemsView[str, Material]: ...


class Material(Object.Object):
    youngs_modulus: float
    poissons_ratio: float
    density: float
    orthotropic_constants: List[float]
    anisotropic_constants: List[float]
