import Manager
import Object
from ctypes import POINTER as POINTER, c_bool as c_bool, c_double as c_double, c_int as c_int, cast as cast
from typing import ItemsView, Iterable, KeysView, List, Optional, ValuesView

BUFFER_SIZE: int


class RuntimeFunctionManager(Manager.AdamsManager):
    def values(self) -> ValuesView[RuntimeFunction]: ...
    def keys(self) -> KeysView[str]: ...
    def items(self) -> ItemsView[str, RuntimeFunction]: ...
    def __getitem__(self, name: str) -> RuntimeFunction: ...
    def __iter__(self) -> Iterable[RuntimeFunction]: ...
    def values_full(self) -> ValuesView[RuntimeFunction]: ...
    def keys_full(self) -> KeysView[str]: ...
    def items_full(self) -> ItemsView[str, RuntimeFunction]: ...


class RuntimeFunction(Object.ObjectBase):
    text_of_expression: str
    argument_names: Optional[List[str]]
    name: str
    def modify(self, **kwargs) -> None: ...
